import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,MessageSquareText,Inbox,Network,FileText,BarChart3,RefreshCw,Send,Upload,AlertTriangle,CheckCircle2,Clock3,ArrowLeft} from 'lucide-react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip} from 'recharts';
import {api} from './services/api';
import './styles.css';

const nav=[['Overview',LayoutDashboard],['Complaint Analyzer',MessageSquareText],['Complaint Queue',Inbox],['Cluster Explorer',Network],['Model Evaluation',BarChart3]];

function App(){
 const [page,setPage]=useState('Overview'); const [overview,setOverview]=useState(null); const [complaints,setComplaints]=useState([]); const [clusters,setClusters]=useState([]); const [selected,setSelected]=useState(null); const [loading,setLoading]=useState(true);
 const refresh=async()=>{setLoading(true); try{const [o,c,k]=await Promise.all([api.overview(),api.complaints(),api.clusters()]);setOverview(o);setComplaints(c.items);setClusters(k.items)}finally{setLoading(false)}};
 useEffect(()=>{refresh()},[]);
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="brandIcon">CG</div><div><div className="brandTitle">CivicLens</div><div className="brandSub">AI grievance intelligence</div></div></div><div className="nav">{nav.map(([name,Icon])=><button className={page===name?'navItem active':'navItem'} onClick={()=>setPage(name)} key={name}><Icon size={18}/><span>{name}</span></button>)}</div><div className="sideNote"><div className="tiny">PROTOTYPE MODE</div><p>AI-assisted analysis only. Human review remains required for low-confidence or sensitive decisions.</p></div></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Citizen grievance intelligence</div><h1>{page}</h1></div><button className="refresh" onClick={refresh}><RefreshCw size={16}/> Refresh</button></header>{loading?<Loading/>:<>{page==='Overview'&&<Overview data={overview} complaints={complaints} clusters={clusters} onSelect={x=>{setSelected(x);setPage('Complaint Detail')}}/>} {page==='Complaint Analyzer'&&<Analyzer onCreated={refresh}/>} {page==='Complaint Queue'&&<Queue complaints={complaints} onSelect={x=>{setSelected(x);setPage('Complaint Detail')}} onRefresh={refresh}/>} {page==='Complaint Detail'&&<Detail complaint={selected} onBack={()=>setPage('Complaint Queue')}/>} {page==='Cluster Explorer'&&<Clusters clusters={clusters}/>} {page==='Model Evaluation'&&<Evaluation/>}</>}</main></div>
}
const Loading=()=> <div className="state"><div className="spinner"></div><p>Loading complaint analytics...</p></div>;
function Stat({label,value,icon:Icon}){return <div className="stat"><div className="statIcon"><Icon size={18}/></div><div><div className="statLabel">{label}</div><div className="statValue">{value??0}</div></div></div>}
function Overview({data,complaints,clusters,onSelect}){return <div className="content"><div className="grid4"><Stat label="Total complaints" value={data.total_complaints} icon={FileText}/><Stat label="High / critical" value={data.high_critical} icon={AlertTriangle}/><Stat label="Low confidence" value={data.low_confidence} icon={Clock3}/><Stat label="Active clusters" value={data.active_clusters} icon={Network}/></div><div className="twoCol"><section className="card"><div className="cardHead"><div><h2>Department distribution</h2><p>Current local complaint set</p></div></div><div className="chart"><ResponsiveContainer width="100%" height={180}><BarChart data={Object.entries(data.department_distribution||{}).map(([name,count])=>({name,count}))}><XAxis dataKey="name" tick={{fontSize:9}} interval={0} angle={-18} textAnchor="end" height={45}/><YAxis allowDecimals={false} tick={{fontSize:9}} width={25}/><Tooltip/><Bar dataKey="count" fill="#4c9b96" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div><div className="bars">{Object.entries(data.department_distribution||{}).map(([k,v])=><div className="barRow" key={k}><div className="barLabel"><span>{k}</span><b>{v}</b></div><div className="barTrack"><div className="barFill" style={{width:`${Math.min(100,v/Math.max(1,data.total_complaints)*100)}%`}}/></div></div>)}</div></section><section className="card"><div className="cardHead"><div><h2>Potential emerging clusters</h2><p>Signals for human review</p></div></div>{clusters.length?<div className="clusterMini">{clusters.slice(0,4).map(c=><div className="clusterRow" key={c.cluster_id}><span className="clusterBadge">#{c.cluster_id}</span><div><b>{c.label}</b><small>{c.complaint_count} complaints · {c.growth}% growth signal</small></div><span className="pill">{c.potential_emerging?'Review':'Stable'}</span></div>)}</div>:<Empty text="No cluster results yet."/>}</section></div><section className="card"><div className="cardHead"><div><h2>Recent complaints</h2><p>Latest locally processed records</p></div></div><ComplaintTable rows={complaints.slice(-6).reverse()} onSelect={onSelect}/></section></div>}
function Analyzer({onCreated}){const [text,setText]=useState('');const [result,setResult]=useState(null);const [busy,setBusy]=useState(false);const submit=async()=>{if(!text.trim())return;setBusy(true);try{const r=await api.predict(text);setResult(r);await api.create(text);onCreated()}finally{setBusy(false)}};return <div className="content"><section className="card analyzer"><div className="cardHead"><div><h2>Analyze a complaint</h2><p>Enter narrative text for department, category, urgency & similarity assistance.</p></div><span className="mode">MOCK MODEL ENABLED</span></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Example: There is a large pothole near the school and vehicles are struggling to pass."/><div className="analyzerFoot"><span>{text.length}/5000 characters</span><button className="primary" onClick={submit} disabled={busy||text.trim().length<3}>{busy?'Analyzing...':<><Send size={16}/> Analyze complaint</>}</button></div></section>{result&&<section className="card"><div className="resultHead"><div><h2>Analysis result</h2><p>AI-assisted output — review before operational use.</p></div><span className={result.review_required?'pill warn':'pill success'}>{result.review_required?'Human review':'Assist-ready'}</span></div><div className="resultGrid"><Result label="Category" value={result.category}/><Result label="Department" value={result.department}/><Result label="Confidence" value={`${Math.round(result.confidence*100)}%`}/><Result label="Urgency" value={result.urgency}/></div><div className="notice"><CheckCircle2 size={18}/><div><b>{result.possible_duplicate?'Possible duplicate detected':'No strong duplicate signal'}</b><p>{result.similar_complaints?.length||0} similar local complaint(s) returned for context.</p></div></div>{result.similar_complaints?.length>0&&<ComplaintTable rows={result.similar_complaints.map(x=>({complaint_id:x.complaint_id,text:x.text,confidence:x.similarity,category:'Similar',department:'—',urgency:'—'}))}/>}</section>}</div>}
const Result=({label,value})=><div className="result"><span>{label}</span><b>{value}</b></div>;
function Queue({complaints,onSelect,onRefresh}){const input=React.useRef();const upload=async(e)=>{const f=e.target.files?.[0];if(!f)return;const form=new FormData();form.append('file',f);await api.batch(form);await onRefresh()};return <div className="content"><section className="card"><div className="cardHead"><div><h2>Complaint queue</h2><p>Local records with filter-ready API support.</p></div><><input ref={input} type="file" accept=".csv" hidden onChange={upload}/><button className="secondary" onClick={()=>input.current?.click()}><Upload size={16}/> Batch CSV</button></></div><ComplaintTable rows={complaints} onSelect={onSelect}/>{!complaints.length&&<Empty text="No complaints match the selected filters."/>}</section></div>}
function ComplaintTable({rows,onSelect}){return <div className="tableWrap"><table><thead><tr><th>Complaint</th><th>Department</th><th>Category</th><th>Urgency</th><th>Confidence</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.complaint_id||i}><td onClick={()=>onSelect?.(r)} className={onSelect?'clickable':''}><div className="complaintText">{r.text}</div><small>{r.complaint_id||'Similarity result'}</small></td><td>{r.department||'—'}</td><td>{r.category||'—'}</td><td><span className="urgency">{r.urgency||'—'}</span></td><td>{r.confidence!=null?`${Math.round(r.confidence*100)}%`:'—'}</td></tr>)}</tbody></table></div>}

function Detail({complaint,onBack}){if(!complaint)return <div className="content"><section className="card"><Empty text="Select a complaint from the queue to view details."/></section></div>;return <div className="content"><button className="backBtn" onClick={onBack}><ArrowLeft size={15}/> Back to queue</button><section className="card detail"><div className="resultHead"><div><div className="eyebrow">{complaint.complaint_id}</div><h2>Complaint detail</h2></div><span className="pill">{complaint.status||'new'}</span></div><div className="detailText">{complaint.text}</div><div className="resultGrid"><Result label="Department" value={complaint.department||'—'}/><Result label="Category" value={complaint.category||'—'}/><Result label="Confidence" value={complaint.confidence!=null?`${Math.round(complaint.confidence*100)}%`:'—'}/><Result label="Urgency" value={complaint.urgency||'—'}/></div><div className="metaGrid"><div><span>Source</span><b>{complaint.source_name||'—'}</b></div><div><span>Location</span><b>{complaint.location_text||'—'}</b></div><div><span>Cluster</span><b>{complaint.cluster_id??'Unassigned'}</b></div><div><span>Created</span><b>{complaint.created_at||'—'}</b></div></div></section></div>}
function Clusters({clusters}){return <div className="content"><div className="grid3">{clusters.map(c=><div className="card clusterCard" key={c.cluster_id}><div className="clusterTop"><span className="clusterBadge">#{c.cluster_id}</span><span className={c.potential_emerging?'pill warn':'pill'}>{c.potential_emerging?'Potential emerging':'Stable'}</span></div><h2>{c.label}</h2><div className="clusterStat"><b>{c.complaint_count}</b><span>complaints</span></div><p>{c.main_category} · growth signal {c.growth}%</p><div className="rep"><b>Representative complaints</b>{c.representative_complaints.map((x,i)=><div key={i}>“{x}”</div>)}</div></div>)}</div>{!clusters.length&&<section className="card"><Empty text="No cluster results yet. Run the local clustering script to generate them."/></section>}</div>}
function Evaluation(){return <div className="content"><section className="card eval"><div className="emptyIcon"><BarChart3 size={24}/></div><h2>Model evaluation</h2><p>Evaluation files are read from <code>data/evaluations/</code>. Train the baseline with the supplied script to populate actual Accuracy, Macro Precision, Macro Recall, Macro F1, Weighted F1, per-class metrics & confusion matrix.</p><div className="evalGrid"><div><b>Baseline</b><span>TF-IDF + Logistic Regression</span></div><div><b>Transformer</b><span>DistilBERT training scaffold</span></div><div><b>Clustering</b><span>HDBSCAN + silhouette/noise metrics</span></div><div><b>API</b><span>Latency measurement hook</span></div></div></section></div>}
const Empty=({text})=><div className="empty"><div className="emptyIcon"><FileText size={22}/></div><p>{text}</p></div>;
createRoot(document.getElementById('root')).render(<App/>);
